config/routes.rb
Rails.application.routes.draw do
  resources :scripts
  resources :libraries
  resources :programminglanguages
  root to: 'welcome#index'
  resources :hacks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/script.rb
class Script < ApplicationRecord
belongs_to :hack
has_and_belongs_to_many :libraries, :join_table =>:scriptslibraries
belongs_to :programminglanguage
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: %i[ show edit update destroy ]

  # GET /scripts or /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1 or /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts or /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to hack_url(@script.hack), notice: "Script was successfully created." }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1 or /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to hack_url(@script.hack), notice: "Script was successfully updated." }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1 or /scripts/1.json
  def destroy
    @script.destroy

    respond_to do |format|
      format.html { redirect_to scripts_url, notice: "Script was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def script_params
      params.require(:script).permit(:hack_id,:programminglanguage_id, :description,:library_ids=>[])
    end
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/scripts/_form.html.erb
<%= form_with(model: script, local: true) do |form| %>
  <% if script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
        <% script.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :hack_id %>
  <div class="field">
    <%= form.label :programminglanguage_id %>
    <%= form.select :programminglanguage_id, Programminglanguage.all.collect{|x|[x.name,x.id]},{include_blank:""}, {onchange: "$('.mylibrary').hide();$('.language'+this.value).show();"} %>
  </div>

  <div class="field">
    <%= form.label :library_ids %>
    <%= form.select :library_ids, Library.all.collect{|x|[x.name,x.id,:class => "mylibrary language#{x.programminglanguage_id}", :style => "display: #{x.programminglanguage_id == script.programminglanguage_id ? "block" : "none"};"]},{}, {multiple:true,size:10} %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Editing Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scripts</h1>

<table>
  <thead>
    <tr>
      <th>Programminglanguage</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scripts.each do |script| %>
      <tr>
        <td><%= script.programminglanguage_id %></td>
        <td><%= script.description %></td>
        <td><%= link_to 'Show', script %></td>
        <td><%= link_to 'Edit', edit_script_path(script) %></td>
        <td><%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Script', new_script_path %>

app/views/scripts/new.html.erb
<h1>New Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Back', scripts_path %>

app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Programminglanguage:</strong>
  <%= @script.programminglanguage_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @script.description %>
</p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>