config/routes.rb
Rails.application.routes.draw do
  resources :scripts
  resources :libraries
  resources :programminglanguages
  root to: 'welcome#index'
  resources :hacks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hack.rb
class Hack < ApplicationRecord
belongs_to :programminglanguage, optional: true
has_many :scripts
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_action :set_hack, only: %i[ show edit update destroy ]

  # GET /hacks or /hacks.json
  def index
    @hacks = Hack.all
  end

  # GET /hacks/1 or /hacks/1.json
  def show
  end

  # GET /hacks/new
  def new
    @hack = Hack.new
  end

  # GET /hacks/1/edit
  def edit
  end

  # POST /hacks or /hacks.json
  def create
    @hack = Hack.new(hack_params)

    respond_to do |format|
      if @hack.save
        format.html { redirect_to hack_url(@hack), notice: "Hack was successfully created." }
        format.json { render :show, status: :created, location: @hack }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hacks/1 or /hacks/1.json
  def update
    respond_to do |format|
      if @hack.update(hack_params)
        format.html { redirect_to hack_url(@hack), notice: "Hack was successfully updated." }
        format.json { render :show, status: :ok, location: @hack }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hacks/1 or /hacks/1.json
  def destroy
    @hack.destroy

    respond_to do |format|
      format.html { redirect_to hacks_url, notice: "Hack was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hack
      @hack = Hack.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hack_params
      params.require(:hack).permit(:programminglanguage_id, :name, :description, :difficult)
    end
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hacks/_form.html.erb
<%= form_with(model: hack, local: true) do |form| %>
  <% if hack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hack.errors.count, "error") %> prohibited this hack from being saved:</h2>

      <ul>
        <% hack.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :programminglanguage_id %>
    <%= form.select :programminglanguage_id, options_for_select(Programminglanguage.all.collect{|x|[x.name,x.id]}), {include_blank: "choisir un langage"} %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
<p><%(1..5).each do |x|%><span id="star<%=x%>" style="background-color:<%=hack.difficult >= x ? "yellow" : "grey"%>;" onclick="<%(x < 5 ? ((x+1)..5) : []).each do |y|%>document.getElementById('star<%=y%>').style.backgroundColor='grey';<%end%><%(1..x).each do |y|%>document.getElementById('star<%=y%>').style.backgroundColor='yellow';<%end%>document.getElementById('mydifficult').value='<%=x%>';">&#9733;</span><%end%></p>
    <%= form.label :difficult %>
    <%= form.hidden_field :difficult,id:"mydifficult" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hacks/edit.html.erb
<h1>Editing Hack</h1>

<%= render 'form', hack: @hack %>

<%= link_to 'Show', @hack %> |
<%= link_to 'Back', hacks_path %>

app/views/hacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hacks</h1>

<table>
  <thead>
    <tr>
      <th>Programminglanguage</th>
      <th></th>
      <th>Description</th>
      <th>Difficult</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hacks.each do |hack| %>
      <tr>
        <td><%= hack.programminglanguage.try(:name) %></td>

        <td><%= hack.name %></td>
        <td><%= hack.description %></td>
        <td><%(1..5).each do |x|%><span id="star<%=x%>" style="background-color:<%=hack.difficult >= x ? "yellow" : "grey"%>;">&#9733;</span><%end%></td>
        <td><%= link_to 'Show', hack %></td>
        <td><%= link_to 'Edit', edit_hack_path(hack) %></td>
        <td><%= link_to 'Destroy', hack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hack', new_hack_path %>

app/views/hacks/new.html.erb
<h1>New Hack</h1>

<%= render 'form', hack: @hack %>

<%= link_to 'Back', hacks_path %>

app/views/hacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Programminglanguage:</strong>
  <%= @hack.programminglanguage.try(:name) %>
</p>

<p>
  <strong>:</strong>
  <%= @hack.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hack.description %>
</p>

<p>
  <strong>Difficult:</strong>
<p><%(1..5).each do |x|%><span id="star<%=x%>" style="background-color:<%=@hack.difficult >= x ? "yellow" : "grey"%>;">&#9733;</span><%end%></p>
</p>

<p>my hack</p>
<%if @hack.scripts.length > 0%>
<ul>
<%@hack.scripts.each do |x|%>
<li><%=x.programminglanguage.try(:name)%> avec <%=x.libraries.collect{|h|h.name}.to_sentence%> : <%=x.description%><%=link_to "voir ce hack",x%></li>
<%end%>
</ul>
<%else%>
<p>quel sont mes hacks ?</p>
<%end%>
<%= render "scripts/form", script: Script.new(hack_id: @hack.id) %> |
<%= link_to 'Edit', edit_hack_path(@hack) %> |
<%= link_to 'Back', hacks_path %>