config/routes.rb
Rails.application.routes.draw do
  resources :scripts
  resources :libraries
  resources :programminglanguages
  root to: 'welcome#index'
  resources :hacks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/programminglanguage.rb
class Programminglanguage < ApplicationRecord
end

app/controllers/programminglanguages_controller.rb
class ProgramminglanguagesController < ApplicationController
  before_action :set_programminglanguage, only: %i[ show edit update destroy ]

  # GET /programminglanguages or /programminglanguages.json
  def index
    @programminglanguages = Programminglanguage.all
  end

  # GET /programminglanguages/1 or /programminglanguages/1.json
  def show
  end

  # GET /programminglanguages/new
  def new
    @programminglanguage = Programminglanguage.new
  end

  # GET /programminglanguages/1/edit
  def edit
  end

  # POST /programminglanguages or /programminglanguages.json
  def create
    @programminglanguage = Programminglanguage.new(programminglanguage_params)

    respond_to do |format|
      if @programminglanguage.save
        format.html { redirect_to programminglanguage_url(@programminglanguage), notice: "Programminglanguage was successfully created." }
        format.json { render :show, status: :created, location: @programminglanguage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @programminglanguage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programminglanguages/1 or /programminglanguages/1.json
  def update
    respond_to do |format|
      if @programminglanguage.update(programminglanguage_params)
        format.html { redirect_to programminglanguage_url(@programminglanguage), notice: "Programminglanguage was successfully updated." }
        format.json { render :show, status: :ok, location: @programminglanguage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @programminglanguage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programminglanguages/1 or /programminglanguages/1.json
  def destroy
    @programminglanguage.destroy

    respond_to do |format|
      format.html { redirect_to programminglanguages_url, notice: "Programminglanguage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programminglanguage
      @programminglanguage = Programminglanguage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def programminglanguage_params
      params.require(:programminglanguage).permit(:name)
    end
end

app/helpers/programminglanguages_helper.rb
module ProgramminglanguagesHelper
end

app/views/programminglanguages/_form.html.erb
<%= form_with(model: programminglanguage, local: true) do |form| %>
  <% if programminglanguage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(programminglanguage.errors.count, "error") %> prohibited this programminglanguage from being saved:</h2>

      <ul>
        <% programminglanguage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programminglanguages/edit.html.erb
<h1>Editing Programminglanguage</h1>

<%= render 'form', programminglanguage: @programminglanguage %>

<%= link_to 'Show', @programminglanguage %> |
<%= link_to 'Back', programminglanguages_path %>

app/views/programminglanguages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programminglanguages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programminglanguages.each do |programminglanguage| %>
      <tr>
        <td><%= programminglanguage.name %></td>
        <td><%= link_to 'Show', programminglanguage %></td>
        <td><%= link_to 'Edit', edit_programminglanguage_path(programminglanguage) %></td>
        <td><%= link_to 'Destroy', programminglanguage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Programminglanguage', new_programminglanguage_path %>

app/views/programminglanguages/new.html.erb
<h1>New Programminglanguage</h1>

<%= render 'form', programminglanguage: @programminglanguage %>

<%= link_to 'Back', programminglanguages_path %>

app/views/programminglanguages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @programminglanguage.name %>
</p>

<%= link_to 'Edit', edit_programminglanguage_path(@programminglanguage) %> |
<%= link_to 'Back', programminglanguages_path %>